### ISSUE TITLE
Inception score comparison 

### ISSUE THREAD

**Issue by ReyhaneAskari** [Zeleni9/pytorch-wgan#4]
To me the fact that your DCGAN is performing better then WGAN-GP is very interesting and surprising. Can you elaborate as to why this happens and what is special about the model/implementation and architecture?

**Comment by Zeleni9** [comment]
Well, I do not have a special explanation since a lot of things depend on the model convergence. The inception score is not really an absolute measure of the model quality. Perhaps the longer training of WGAN-GP would yield somewhat better inception score, but the main difference of the models is WGAN-GP give more stability into training with different and more complex dataset than CIFAR or mnist.
